sudo: required
dist: trusty
language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - sudo pip install -r requirements.txt
script:
    - sudo python3 -c "import kickthemout;"

branches:
  only:
  - master

addons:
  apt:
    packages:
      - nmap

notifications:
  email:
    on_success: never
    on_failure: always
