language: python
sudo: required
python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip3 install codecov
    - pip3 install -r requirements.txt
script:
    - sudo coverage run kickthemout.py
after_success:
  - codecov

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always