language: python
sudo: required
python:
    - "3.4"
    - "3.5"
    - "3.6"
dist: trusty
env:
  - COVERAGE_FILE=/tmp/.coverage

install:
    - pip3 install coveralls
    - pip3 install -r requirements.txt
script:
    - sudo -H coverage run kickthemout.py
after_success:
  - coveralls

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always